---
- name: remove packages
  apt:
    name: "{{ apt_remove_packages }}"
    state: absent

- name: install default packages
  apt:
    name: "{{ apt_default_packages }}"
    state: present

- name: install extra packages
  apt:
    name: "{{ apt_extra_packages }}"
    state: present

